### ISSUE TITLE
有关 django-rest-swagger Authorization 的问题想请教一下

### ISSUE THREAD

**Issue by yuchunyu97** [jianshijiuyou/django-rest-framework-api-guide#4]
Swagger UI 页面上通过 Authorize按钮 设置了 apiKey 的认证方式，为什么通过 Swagger UI 发送的请求里，request headers 里没有 Authorization 字段？
请问设置完了认证信息是所有的请求都会携带认证信息吗？
求大佬赐教 =.=

**Comment by jianshijiuyou** [comment]
@yuchunyu97 前端我不太清楚，不过应该是每次请求都需要手动设置请求头吧。

**Comment by JefferShell** [comment]
抓包分析下！

**Comment by yuchunyu97** [comment]
@jianshijiuyou 不知道你用没用过 django swagger，settings.py 里是这么写的
```python
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'JWT': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization',
            'description': 'Json Web Token 可以通过登录获取'
        },
    },
    'LOGIN_URL': 'rest_framework:login',
    'LOGOUT_URL': 'rest_framework:logout',
    'SHOW_REQUEST_HEADERS': True,
    'JSON_EDITOR': True,
}
```

然后 Swagger UI 上是这个样子：
<img width="1440" alt="qq20180724-152601 2x" src="https://user-images.githubusercontent.com/18714179/43123202-0705147e-8f56-11e8-90f3-a1a67a45a406.png">

不知道是那少写了什么，发送的请求就是没有Header的认证信息

**Comment by jianshijiuyou** [comment]
@yuchunyu97 没用过，浏览器 F12 抓包看下，没有就是你少写了什么，看看 swagger 的文档吧
