### ISSUE TITLE
尝试优化了一下翻译

### ISSUE THREAD

**Issue by Phishion** [jianshijiuyou/django-rest-framework-api-guide#5]
http://drf.jiuyou.info/#/django/django查询?id=跨越关系查找
当时看的时候有点难理解，尝试优化了一下翻译

它也可以倒退。要引用“反向”关系，只需使用模型的小写名称即可。

此示例检索所有至少有一个 headline 包含 'Lennon' 的 Entry 的 Blog 对象：

Blog.objects.filter(entry__headline__contains='Lennon')
>如果您要跨多个关系进行筛选，并且其中一个中间模型的值不符合筛选条件，Django 会把它看作是空的（所有的值都是 NULL），但是它是有效的，在那里有对象。所有这一切意味着不会出现任何错误。例如，在这个过滤器中：

**如果您要跨多个关系进行筛选，并且其中一些实例的中间模型不符合筛选条件，Django 会把这些实例缺失的值当做空值来看待（所有的值都会是 NULL），但是它仍然会被当做一个有效的对象。所以这意味着并不会产生报错信息，例如，在这个过滤器中：**

Blog.objects.filter(entry__authors__name='Lennon')
>（如果有相关的 Author 模型），如果没有 Author 与某个条目相关联，则会将其视为没有附加 name，而不是由于缺少 Author 而引发错误。通常这正是你希望的结果。唯一可能引起混淆的情况是如果你使用 isnull。从而：

**（这里我们假设有一个相关联的 Author 模型），如果一个 author 没有与某个 entry  条目相关联，它（在查询语句上）等同于没有附加 name，总好过因为这个条目缺少 author 抛出错误。通常这正是你希望发生的结果，唯一可能引起混淆的情况是如果你使用 isnull。例如：**

Blog.objects.filter(entry__authors__name__isnull=True)
>将返回 Author 上具有空 name 的 Blog 对象以及 entry 上具有空 Author 的 Blog 对象。如果你不想要后者，你可以这样写：

**这里将返回 author 上 name 的值真的为空的 Blog 对象以及 entry 没有 author 关联的 Blog 对象。如果你不想要后者，你可以这样写：**

Blog.objects.filter(entry__authors__isnull=False, entry__authors__name__isnull=True)

**Comment by jianshijiuyou** [comment]
@Phishion 谢谢，你可以提交 PR，我会合并进去
